### ISSUE TITLE
a segment fault

### ISSUE THREAD

**Issue by mszbing** [begeekmyfriend/bplustree#1]
-- B+tree setting...
Set b+tree non-leaf order (3 < order <= 64 e.g. 7): 3
Set b+tree leaf entries (<= 64 e.g. 10): 3
Please input command (Type 'h' for help): i 1-20
Please input command (Type 'h' for help): d
node: 19
+-------node: 7 13
|       +-------node: 3 5
|       |       +-------leaf: 1 2
|       |       +-------leaf: 3 4
|       |       +-------leaf: 5 6
|       +-------node: 9 11
|       |       +-------leaf: 7 8
|       |       +-------leaf: 9 10
|       |       +-------leaf: 11 12
|       +-------node: 15 17
|               +-------leaf: 13 14
|               +-------leaf: 15 16
|               +-------leaf: 17 18
+-------node:
        +-------node:
                +-------leaf: 19 20
Please input command (Type 'h' for help): r 19
./demo_build.sh: 行 7: 24789 段错误               (核心已转储) ./bin/bplustree_demo

**Comment by begeekmyfriend** [comment]
Fixed https://github.com/begeekmyfriend/bplustree/commit/896ff30dda5faf40412eb110a526cc90b872bdc8
Thank you for your check!
