### ISSUE TITLE
执行./coverage_build.sh 提示 node_seek: Assertion `len == _block_size' failed.

### ISSUE THREAD

**Issue by LiDing0611** [begeekmyfriend/bplustree#10]
您好 前辈 执行./coverage_build.sh 时有如下错误
please wait about 10 seconds for test case generation...
-- The C compiler identification is GNU 4.3.4
-- The CXX compiler identification is GNU 4.3.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/liding/coding/bplustree-disk-io/build
Scanning dependencies of target bplustree_coverage
[ 50%] Building C object tests/CMakeFiles/bplustree_coverage.dir/__/lib/bplustree.c.o
/home/liding/coding/bplustree-disk-io/lib/bplustree.c: In function ‘node_fetch’:
/home/liding/coding/bplustree-disk-io/lib/bplustree.c:128: warning: implicit declaration of function ‘pread’
/home/liding/coding/bplustree-disk-io/lib/bplustree.c: In function ‘node_flush’:
/home/liding/coding/bplustree-disk-io/lib/bplustree.c:154: warning: implicit declaration of function ‘pwrite’
[100%] Building C object tests/CMakeFiles/bplustree_coverage.dir/bplustree_coverage.c.o
Linking C executable ../bin/bplustree_coverage
[100%] Built target bplustree_coverage
Scanning dependencies of target coverage
Deleting all .da files in . and subdirectories
Done.
config node order:39 and leaf entries:39
**bplustree_coverage: /home/liding/coding/bplustree-disk-io/lib/bplustree.c:144: node_seek: Assertion `len == _block_size' failed.
make[3]: *** [tests/CMakeFiles/coverage] Aborted
make[2]: *** [tests/CMakeFiles/coverage.dir/all] Error 2
make[1]: *** [tests/CMakeFiles/coverage.dir/rule] Erro**

**Comment by begeekmyfriend** [comment]
Note: You need to delete the existing `/tmp/coverage.index` first for this testing!

**Comment by LiDing0611** [comment]
> Note: You need to delete the existing `/tmp/coverage.index` first for this testing!
我执行了删除`/tmp/coverage.index`的命令 还是不可以 一样的错误 
执行./demo_build.sh都是没问题的

**Comment by begeekmyfriend** [comment]
你的机器是什么配置？32-bit等

**Comment by LiDing0611** [comment]
是64的

**Comment by begeekmyfriend** [comment]
没法复现，打印一下`len`和`_block_size`分别多少

**Comment by LiDing0611** [comment]
好的 我试下 或者换个环境吧 多谢多谢

**Comment by begeekmyfriend** [comment]
我在Ubuntu 16.04上很好地执行，你是否改了源代码？
![image](https://user-images.githubusercontent.com/6031938/61635196-96cc0a80-acc5-11e9-9478-220beea358f0.png)

**Comment by LiDing0611** [comment]
我的机器是SUSE Linux  看你这个代码比较精简 有在这个基础上加Anti-Caching的想法

**Comment by begeekmyfriend** [comment]
Then there are bugs in your modification absolutely.

**Comment by LiDing0611** [comment]
我还没开始加东西啊 就是执行你的这个代码 找了一下午没找出原因  会不会SUSE环境的影响吧 我刚试了下redhat 是ok的

**Comment by begeekmyfriend** [comment]
打印一下`len`和`_block_size`吧，这里可是用的系统调用`pread`，搞不定SUSE系统有bug呢

**Comment by LiDing0611** [comment]
嗯嗯 我找到原因了 我这个/tmp下还有一个coverage.index.boot文件 需要把这个也删掉才可以运行  还有一个小问题 你那个测试性能读写时间的结果是保存在了哪个文件里

**Comment by begeekmyfriend** [comment]
我不记得有测试性能读写时间的benchmark

**Comment by LiDing0611** [comment]
https://www.jianshu.com/p/a8d3432f3840   我看这个里有 没有的话我自己加一个

**Comment by begeekmyfriend** [comment]
没想到我的项目都有人改写并写成博客了，行，你自己加吧

**Comment by LiDing0611** [comment]
哈哈 点个赞 因为写的很棒

**Comment by begeekmyfriend** [comment]
我怀疑他这是内存版本，不然怎么会快400倍……

**Comment by begeekmyfriend** [comment]
哦，看错了，他之前是链表版本

**Comment by LiDing0611** [comment]
我还一直以为这个blog也是你更新的

**Comment by begeekmyfriend** [comment]
我会为了一个repo去写blog，还系列？

**Comment by begeekmyfriend** [comment]
我会为了一个repo去写blog，还系列？
