### ISSUE TITLE
支持单用户写入,多用户查询吗?

### ISSUE THREAD

**Issue by wxingda** [begeekmyfriend/bplustree#11]

**Comment by begeekmyfriend** [comment]
你是说多线程是吧，`struct bplus_tree`里放一把全局锁，每个API前后`acquire/release`一下即可。

**Comment by wxingda** [comment]
但是这种大锁会影响效率啊

**Comment by begeekmyfriend** [comment]
那就看你自己怎么优化了，减小锁的粒度等等，no free lunch...

**Comment by wxingda** [comment]
这个项目的api设计还是挺不错的,支持range查询,但是如果用在高并发的场景下就不太合适了

**Comment by begeekmyfriend** [comment]
给钱就行;-P

**Comment by begeekmyfriend** [comment]
嗨，虽然这个issue已经关闭一年多了，只是最近看到一篇讨论操作系统的文章[《被神话的Linux, 一文带你看清Linux在多核可扩展性设计上的不足》](https://blog.csdn.net/juS3Ve/article/details/100012006)一时想起了这个帖子。
根据文章关于微内核资源竞争串行化的设想，我觉得可以设计这么一种方案，避免对B+树这个资源大户加锁。比如你可以在上层设计一个server/worker模式，worker线程把每个CRUD操作进行某种队列操作，server线程作为调度器对出队列串行执行实际的CRUD。这样一来竞争开销只在于worker线程的队列操作，而不用对B+树这个数据结构上锁，CPU利用率也会很高。只要控制好时序，就能正确执行多用户操作。

**Comment by wxingda** [comment]
我现在用了https://github.com/malbrain/Btree-source-code ，这是一系列无锁的B树，性能和稳定性都是不错的

**Comment by begeekmyfriend** [comment]
B树不是不支持get_range么，好吧，待到有空我会参照他的样子做成无锁模型，性能绝对不差。To be continued...
